spring:
  profiles:
    active:
      - dev
---
spring:
  profiles: dev
  application: 
    name: CodeSharingCommunityConfig_dev
---
spring:
  profiles: test
  application: 
    name: CodeSharingCommunityConfig_test
