server:
  port: 80
  servlet:
    context-path: /
  max-http-header-size: 128KB
spring:
  profiles: dev
  application:
    # 自己在 eureka 里的唯一标识
    name: CodeSharingCommunityConsumer
  redis:
    host: localhost
    password: pyb***20000112
    port: 6379
    jedis:
      pool:
        max-active: 60
        max-wait: 60
        max-idle: 10
eureka:
  client:
    service-url:
      # Eureka 管理, 如为集群模式, 则应注册到所有 eureka
      defaultZone: http://localhost:7001/eureka/
      # 注册自己进 Eureka
    register-with-eureka: true
  instance:
    # 自己的唯一名称
    instance-id: CodeSharingCommunity_客户端
    prefer-ip-address: true
feign:
  hystrix:
    # 开启 hystrix 降级机制
    # 降级即为服务端宕机时, 一个备用的响应返回
    enabled: true
hystrix:
  command:
    default:
      execution:
        #设置超时时间
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        semaphore:
          maxConcurrentRequests: 20
logging:
  config: classpath:log4j2.xml
---
