server:
  port: 80
  servlet:
    context-path: /
spring:
  application:
    # 自己在 eureka 里的唯一标识
    name: CodeSharingCommunityConsumer
eureka:
  client:
    service-url:
      # Eureka 管理, 如为集群模式, 则应注册到所有 eureka
      defaultZone: http://localhost:7001/eureka/
      # 注册自己进 Eureka
    register-with-eureka: true
  instance:
    # 自己的唯一名称
    instance-id: CodeSharingCommumity_客户端
    prefer-ip-address: true
feign:
  hystrix:
    # 开启 hystrix 降级机制
    # 降级即为服务端宕机时, 一个备用的响应返回
    enabled: true
hystrix:
  command:
    default:
      execution:
        #设置超时时间
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 60000
        semaphore:
          maxConcurrentRequests: 20
logging:
  config: classpath:log4j2.xml
csc:
  cors:
    # 该配置代表本服务允许访问的域名, 如想设置为允许所有域名访问,
    # 则无法保证用户持续登录认证问题
    allow-ip: http://112.124.30.43:8080/, 112.124.30.43:8080/
