server:
  port: 9527
  
  servlet:
    context-path: /

spring:
  application:
    name: CodeSharingCommunityZuulGateway
  cloud:
    config:
      discovery:
        enabled: true
    loadbalancer:
      ribbon:
        enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 20
      maximum-pool-size: 100
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      username: root
      password: pyb***20000112
      jdbc-url: jdbc:mysql://localhost:3306/pdsu_csc?useSSL=false&serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    password: pyb***20000112
    port: 6379
    jedis:
      pool:
        max-active: 60
        max-wait: 60
        max-idle: 10
  profiles: dev

mybatis:
  mapper-locations:
    - classpath:mybatis/mapper/*.xml
  type-aliases-package: com.pdsu.csc.bean
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instance-id: CodeSharingCommunity_路由网关
    prefer-ip-address: true
zuul:
  ignored-services: '*'
  sensitive-headers:
  add-proxy-headers: false
  add-host-header: true
  # prefix: /api
  routes:
    study:
      path: /**
      service-id: CodeSharingCommunityConsumer
  ignored-patterns: /user/login, /user/loginstatus

info:
  app.name: CodeSharingCommunity_路由网关_01
  company.name: www.halfdream.cn/半梦的个人网址
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

logging:
  config: classpath:log4j2.xml
---
